export enum MapChType {
    bigmap = "海关",
    factory4_day = "工厂 白",
    factory4_night = "工厂 夜",
    interchange = "立交桥",
    laboratory = "实验室",
    lighthouse = "灯塔",
    rezervbase = "储备站",
    sandbox = "中心区",
    sandbox_high = "中心区",
    shoreline = "海岸线",
    tarkovstreets = "街区",
    woods = "森林",
    sandbox = "中心区",
}